export const ACTION_STRING = {
  authLogin: "AUTH_LOGIN",
  authLogout: "AUTH_LOGOUT",
  register: "REGISTER",
  authReset: "AUTH_RESET",
  pending: "_PENDING",
  fulfilled: "_FULFILLED",
  rejected: "_REJECTED",
  getProducts: "_GET_PRODUCTS",
  createProduct: "_CREATE_PRODUCT",
  updateProducts: "_UPDATE_PRODUCT",
  getDetailProduct: "_GET_PRODUCT_DETAIL",
  getProfile: "_GET_PROFILE",
  updateProfile: "_UPDATE_PROFILE",
  getPromos: "_GET_PROMOS",
};